workouts = [
  {
    name: "Shoulder Press",
    image: "",
    equipment: "dumbbell",
    muscleGroup: ["shoulder", "chest"],
    difficulty: "easy",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
  {
    name: "",
    image: "",
    equipment: "bodyweight",
    muscleGroup: [""],
    difficulty: "",
  },
];

export { workouts };
