const workouts = [
  {
    name: "Shoulder Press",
    image: "shoulder_press_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["shoulder", "chest"],
    difficulty: "easy",
  },
  {
    name: "Push-ups",
    image: "pushups_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["chest", "triceps"],
    difficulty: "moderate",
  },
  {
    name: "Bicep Curls",
    image: "bicep_curls_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["biceps"],
    difficulty: "moderate",
  },
  {
    name: "Tricep Extensions",
    image: "tricep_extensions_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["triceps"],
    difficulty: "moderate",
  },
  {
    name: "Dumbbell Rows",
    image: "dumbbell_rows_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["back"],
    difficulty: "moderate",
  },
  {
    name: "Dumbbell Lunges",
    image: "dumbbell_lunges_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["legs", "glutes"],
    difficulty: "moderate",
  },
  {
    name: "Dumbbell Bench Press",
    image: "dumbbell_bench_press_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["chest", "triceps"],
    difficulty: "moderate",
  },
  {
    name: "Renegade Rows",
    image: "renegade_rows_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["core", "back"],
    difficulty: "difficult",
  },
  {
    name: "Dumbbell Deadlifts",
    image: "dumbbell_deadlifts_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["back", "hamstrings"],
    difficulty: "moderate",
  },
  {
    name: "Dumbbell Front Raises",
    image: "dumbbell_front_raises_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["shoulder"],
    difficulty: "moderate",
  },
  {
    name: "Dumbbell Lateral Raises",
    image: "dumbbell_lateral_raises_image.jpg",
    equipment: "dumbbell",
    muscleGroup: ["shoulder"],
    difficulty: "moderate",
  },
  {
    name: "Squats",
    image: "squats_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["legs", "glutes"],
    difficulty: "easy",
  },
  {
    name: "Plank",
    image: "plank_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["core"],
    difficulty: "easy",
  },
  {
    name: "Lunges",
    image: "lunges_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["legs", "glutes"],
    difficulty: "moderate",
  },
  {
    name: "Pull-ups",
    image: "pullups_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["back", "biceps"],
    difficulty: "difficult",
  },
  {
    name: "Dips",
    image: "dips_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["triceps", "chest"],
    difficulty: "moderate",
  },
  {
    name: "Burpees",
    image: "burpees_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["full body"],
    difficulty: "difficult",
  },
  {
    name: "Mountain Climbers",
    image: "mountain_climbers_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["core", "cardio"],
    difficulty: "moderate",
  },
  {
    name: "Russian Twists",
    image: "russian_twists_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["obliques", "core"],
    difficulty: "moderate",
  },
  {
    name: "Jumping Jacks",
    image: "jumping_jacks_image.jpg",
    equipment: "bodyweight",
    muscleGroup: ["cardio"],
    difficulty: "easy",
  },
  
];

export { workouts };
